server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:12000/bonus_system
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  kafka:
    consumer:
      group-id: transaction-event-processor
      auto-offset-reset: earliest
    bootstrap-servers: localhost:9092

transactions:
  topic-name: TransactionEvents
  messages-per-request: 1

data:
  folder: /home/nchernetsov/Education/hackaton/rosbank-12-2019/data-folder
  scan-frequency-ms: 10000

logging:
  level:
    ru.rosbank.hackathon.bonusSystem: DEBUG
