server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:12000/bonus_system
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

data:
  folder: /home/nchernetsov/Education/hackaton/rosbank-12-2019/data-folder
  scan-frequency-ms: 10000

logging:
  level:
    ru.rosbank.hackathon.bonusSystem: DEBUG
